### ISSUE TITLE
Inconsistent CWL test failures

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil#1037] opened 2016-07-01 03:08 UTC
see [http://jenkins.cgcloud.info/job/toil-pull-requests/1567/](http://jenkins.cgcloud.info/job/toil-pull-requests/1567/)

**Comment by hannes-ucsc** [comment] 2016-07-01 16:21
That build is for the robust clean PR. To prove that this is not caused by that PR, have you seen this on any other PR or the master build?

**Comment by JakeNarkizian** [comment] 2016-07-01 20:57
Both CWL tests failed with the same error on my machine on the latest master branch. I also found these but one of them includes changes to CWL... 
[http://jenkins.cgcloud.info/job/toil-pull-requests/1554/#showFailuresLink](http://jenkins.cgcloud.info/job/toil-pull-requests/1554/#showFailuresLink)
[http://jenkins.cgcloud.info/job/toil-pull-requests/1549/#showFailuresLink](http://jenkins.cgcloud.info/job/toil-pull-requests/1549/#showFailuresLink)

**Comment by hannes-ucsc** [comment] 2016-07-01 21:23
AFAICT, those are different, unrelated errors. No proof that this issue occurs outside PR #916. The builds of other PRs are succeeding and so are master builds. So far only PR #916 and supposedly master on your machine expose this behavior.

**Comment by hannes-ucsc** [comment] 2016-07-01 21:36
```
WARNING:toil.leader:w/r/jobu1V5w6:	INFO:rdflib:RDFLib Version: 4.2.1
WARNING:toil.leader:w/r/jobu1V5w6:	INFO:toil.job:CACHE: Read file with ID '7/v/tmpKkWj1p.tmp' from the cache.
WARNING:toil.leader:w/r/jobu1V5w6:	['docker', 'pull', 'debian:8']
WARNING:toil.leader:w/r/jobu1V5w6:	INFO:cwltool:['docker', 'pull', 'debian:8']
WARNING:toil.leader:w/r/jobu1V5w6:	Pulling repository docker.io/library/debian
WARNING:toil.leader:w/r/jobu1V5w6:	Tag 8 not found in repository docker.io/library/debian
WARNING:toil.leader:w/r/jobu1V5w6:	Got workflow error
```

@jvivian ran into a similar issue earlier today, too. Since the other build are working, I'm going to assume that it was a Dockerhub glitch and closing this. If you believe this is in error, reopen.

**Closed by hannes-ucsc** 2016-07-01 21:36 UTC
Labels: bug, discuss, need info
