### ISSUE TITLE
Toil can't print its help

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#2117] opened 2018-03-08 22:09 UTC
With Toil 3.14.0, the code to print help crashes because one of the modules it is trying to operate on doesn't have a docstring.

```
[anovak@kolossus toil-vg]$ pip install --user toil
Collecting toil
  Using cached toil-3.14.0.tar.gz
Requirement already satisfied: bd2k-python-lib>=1.14a1.dev35 in /cluster/home/anovak/.local/lib/python2.7/site-packages (from toil)
Requirement already satisfied: dill==0.2.5 in /cluster/home/anovak/python/lib/python2.7/site-packages (from toil)
Requirement already satisfied: six>=1.10.0 in /cluster/home/anovak/python/lib/python2.7/site-packages (from toil)
Requirement already satisfied: future in /cluster/home/anovak/.local/lib/python2.7/site-packages (from toil)
Requirement already satisfied: requests==2.18.4 in /cluster/home/anovak/.local/lib/python2.7/site-packages (from toil)
Requirement already satisfied: docker==2.5.1 in /cluster/home/anovak/.local/lib/python2.7/site-packages (from toil)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /cluster/home/anovak/.local/lib/python2.7/site-packages (from requests==2.18.4->toil)
Requirement already satisfied: certifi>=2017.4.17 in /cluster/home/anovak/.local/lib/python2.7/site-packages (from requests==2.18.4->toil)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /cluster/home/anovak/.local/lib/python2.7/site-packages (from requests==2.18.4->toil)
Requirement already satisfied: idna<2.7,>=2.5 in /cluster/home/anovak/.local/lib/python2.7/site-packages (from requests==2.18.4->toil)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /cluster/home/anovak/.local/lib/python2.7/site-packages (from docker==2.5.1->toil)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /cluster/home/anovak/.local/lib/python2.7/site-packages (from docker==2.5.1->toil)
Requirement already satisfied: docker-pycreds>=0.2.1 in /cluster/home/anovak/.local/lib/python2.7/site-packages (from docker==2.5.1->toil)
Requirement already satisfied: websocket-client>=0.32.0 in /cluster/home/anovak/.local/lib/python2.7/site-packages (from docker==2.5.1->toil)
Installing collected packages: toil
  Running setup.py install for toil ... done
Successfully installed toil-3.14.0
[anovak@kolossus toil-vg]$ toil --version
3.14.0
[anovak@kolossus toil-vg]$ toil --help
Traceback (most recent call last):
  File "/cluster/home/anovak/.local/bin/toil", line 11, in <module>
    load_entry_point('toil==3.14.0', 'console_scripts', 'toil')()
  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/utils/toilMain.py", line 19, in main
    printHelp(modules)
  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/utils/toilMain.py", line 62, in printHelp
    descriptions='\n'.join("%s - %s" % (n, m.__doc__.strip()) for n, m in iteritems(modules))))
  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/utils/toilMain.py", line 62, in <genexpr>
    descriptions='\n'.join("%s - %s" % (n, m.__doc__.strip()) for n, m in iteritems(modules))))
AttributeError: 'NoneType' object has no attribute 'strip'
[anovak@kolossus toil-vg]$ 
```

**Comment by DailyDreaming** [comment] 2018-03-09 01:06
This is a duplicate of #2081.  We haven't done a new release yet to address the issue, but the fix should be in 3.15.0 and is in the current build if built from source.

**Closed** 2018-03-12 19:11 UTC
