### ISSUE TITLE
AssertionError in AWS job store

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#676] opened 2016-02-10 20:45 UTC
```
WARNING:toil.leader:The jobWrapper seems to have left a log file, indicating failure: 942269e6-1f1c-4eb5-84c1-f24945c32ada
WARNING:toil.leader:Reporting file: 942269e6-1f1c-4eb5-84c1-f24945c32ada
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:       —TOIL WORKER OUTPUT LOG—
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:       Traceback (most recent call last):
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:         File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 266, in main
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:           job = Job._loadJob(jobWrapper.command, jobStore)
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 944, in _loadJob
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:           return cls._unpickle(userModule, fileHandle)
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 965, in _unpickle
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:           return unpickler.load()
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:       EOFError
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:       Exiting the worker because of a failed jobWrapper on host ip-172-31-44-252
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:       ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-44-252
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:       WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 942269e6-1f1c-4eb5-84c1-f2494
5c32ada to 0
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:       Exception in thread Thread-5:
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:       Traceback (most recent call last):
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:         File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:           self.run()
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:         File "/usr/local/lib/python2.7/dist-packages/bd2k/util/threading.py", line 38, in run
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:           super( ExceptionalThread, self ).run( )
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:         File "/usr/lib/python2.7/threading.py", line 754, in run
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:           self.__target(*self.__args, **self.__kwargs)
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:         File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 758, in writer
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:           assert False
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:       AssertionError
WARNING:toil.leader:942269e6-1f1c-4eb5-84c1-f24945c32ada:
WARNING:toil.leader:Job: 942269e6-1f1c-4eb5-84c1-f24945c32ada is completely failed
```

**Comment by hannes-ucsc** [comment] 2016-02-10 21:26
The assertion fails due to a FileInfo object having neither inlined content from SDB nor an object version from S3. This might fall into the corrupted job store category.

**Comment by hannes-ucsc** [comment] 2016-05-10 17:38
@cket, didn't you fix this recently?

**Comment by cket** [comment] 2016-05-10 17:52
i have a similar bugfix on the Google job store branch, I think it solves this issue too. Should I pull it out into its own PR?

**Comment by hannes-ucsc** [comment] 2016-05-11 00:53
Up to you, @cket. The Google branch will be reviewed and hopefully merged soon. The only thing I ask for is that this issue is referenced in a commit title.

**Comment by cket** [comment] 2016-05-18 20:54
I looked into this more today and while it's similar to #832 it isn't the same bug. Can you give me more context for the failure? Was it raised in sort test?

**Comment by hannes-ucsc** [comment] 2016-05-18 22:53
Unfortunately, I don't have more contextual information. I don't think it was a Jenkins build because I just installed the Lucene indexer on Jenkins and searched for one of the UUIDs in the output I posted.

**Comment by cket** [comment] 2016-05-23 20:23
I spent several hours unsuccessfully looking for bugs that could cause this exception and since the behavior is unreproducible without more information I think we should either close or backlog this issue.

**Comment by cket** [comment] 2016-12-02 21:50
Haven't seen this reoccur, closing

**Closed** 2016-12-02 21:51 UTC
Labels: bug
