### ISSUE TITLE
update ec2 instance types

### ISSUE THREAD

**Issue by tpesout** [BD2KGenomics/toil#1931] opened 2017-10-19 23:28 UTC
I hear CGCloud is getting deprecated, but the aws provisioner still depends on instance types defined in it.  When this gets ported over to toil (or earlier, if possible), please update with all the instance types.  Specifically I'd like to use the r4 instances ([see here](https://aws.amazon.com/ec2/pricing/on-demand/)), but cannot.

https://github.com/BD2KGenomics/cgcloud/blob/master/lib/src/cgcloud/lib/ec2.py @158

**Comment by jessebrennan** [comment] 2017-10-20 18:33
duplicate of #1893

**Closed by jessebrennan** 2017-10-20 18:33 UTC
