### ISSUE TITLE
launch-cluster waits forever for the Toil appliance to start

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1831] opened 2017-08-15 19:47 UTC
To fix #1830, I uploaded my SSH public key to AWS.

```
$ aws ec2 import-key-pair --key-name "$(whoami)" --public-key-material "$(cat ~/.ssh/id_rsa.pub)"
{
    "KeyName": "anovak", 
    "KeyFingerprint": "14:f5:f3:39:a6:cf:c8:27:dd:78:7c:12:cc:22:85:3a"
}
```

Now I can start up an instance, but it looks like Docker never starts the Toil appliance:

```
$ TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:3.9.1 toil launch-cluster novakcluster --nodeType=t2.micro -z us-west-2a --keyPairName=anovak
INFO:toil.lib.bioio:Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
INFO:toil.utils.toilLaunchCluster:Using aws provisioner.
INFO:toil:Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
INFO:toil:Using default docker name of toil as TOIL_DOCKER_NAME is not set.
INFO:toil:Overriding docker appliance of quay.io/ucsc_cgl/toil:3.10.0a1-dd898ab49f8a6605c4c88ef18df8fb384e4392f5-dirty with quay.io/ucsc_cgl/toil:3.9.1 from TOIL_APPLIANCE_SELF.
INFO:toil.provisioners.aws.awsProvisioner:Launching non-preemptable leader
INFO:cgcloud.lib.ec2:Creating t2.micro instance(s) ... 
INFO:toil.provisioners.aws.awsProvisioner:Waiting for toil_leader to enter 'running' state...
INFO:toil.provisioners.aws.awsProvisioner:... toil_leader is running
INFO:toil.provisioners.aws.awsProvisioner:Waiting for ip...
INFO:toil.provisioners.aws.awsProvisioner:...got ip
INFO:toil.provisioners.aws.awsProvisioner:Waiting for ssh port to open...
INFO:toil.provisioners.aws.awsProvisioner:...ssh port open
INFO:toil.provisioners.aws.awsProvisioner:Attempting to establish SSH connection...
Warning: Permanently added 'ec2-54-149-8-63.us-west-2.compute.amazonaws.com,54.149.8.63' (RSA) to the list of known hosts.
Connection to ec2-54-149-8-63.us-west-2.compute.amazonaws.com closed.
INFO:toil.provisioners.aws.awsProvisioner:...SSH connection established.
INFO:toil.provisioners.aws.awsProvisioner:Waiting for docker on ec2-54-149-8-63.us-west-2.compute.amazonaws.com to start...
Warning: Permanently added 'ec2-54-149-8-63.us-west-2.compute.amazonaws.com,54.149.8.63' (RSA) to the list of known hosts.
Connection to ec2-54-149-8-63.us-west-2.compute.amazonaws.com closed.
INFO:toil.provisioners.aws.awsProvisioner:Docker daemon running
INFO:toil.provisioners.aws.awsProvisioner:Waiting for toil_leader Toil appliance to start...
Warning: Permanently added 'ec2-54-149-8-63.us-west-2.compute.amazonaws.com,54.149.8.63' (RSA) to the list of known hosts.
Connection to ec2-54-149-8-63.us-west-2.compute.amazonaws.com closed.
INFO:toil.provisioners.aws.awsProvisioner:...Still waiting, trying again in 10sec...
Warning: Permanently added 'ec2-54-149-8-63.us-west-2.compute.amazonaws.com,54.149.8.63' (RSA) to the list of known hosts.
Connection to ec2-54-149-8-63.us-west-2.compute.amazonaws.com closed.
INFO:toil.provisioners.aws.awsProvisioner:...Still waiting, trying again in 10sec...
...
```

It continues like this for many minutes. Something must have gone wrong with the instance configuration.

**Comment by joelarmstrong** [comment] 2017-08-15 20:00
It connects fine, but it doesn't detect the toil_leader container running. That's because the image you specified (tagged 3.9.1) doesn't exist. Arguably it should check for the existence of the tag before launching the cluster.

This is probably a dupe of #1707, #1697, #1688.

**Comment by adamnovak** [comment] 2017-08-15 20:19
Oh, it looks like there is a `3.9.1-367ba6d4fdb76362128a...` but no `3.9.1`.

I was led astray by http://toil.readthedocs.io/en/3.9.1/running/running.html#envars:

```
TOIL_APPLIANCE_SELF 

The fully qualified reference for the Toil Appliance you wish to use, in the form REPO/IMAGE:TAG. quay.io/ucsc_cgl/toil:3.6.0 and cket/toil:3.5.0 are both examples of valid options. Note that since Docker defaults to Dockerhub repos, only quay.io repos need to specify their registry.
```

If `quay.io/ucsc_cgl/toil:3.6.0` works, and the current version is `3.9.1`, then `quay.io/ucsc_cgl/toil:3.9.1` really ought to work.

**Comment by joelarmstrong** [comment] 2017-08-15 21:24
Yeah, i think the tagging is probably a non-automated, and undocumented,
part of the release process. I don't have a connection here, but someone
should just go ahead and tag the 3.9.1 to the container with the correct
commit.

On Aug 15, 2017 1:20 PM, "Adam Novak" <notifications@github.com> wrote:

Oh, it looks like there is a 3.9.1-367ba6d4fdb76362128a... but no 3.9.1.

I was led astray by http://toil.readthedocs.io/en/
3.9.1/running/running.html#envars:

TOIL_APPLIANCE_SELF

The fully qualified reference for the Toil Appliance you wish to use,
in the form REPO/IMAGE:TAG. quay.io/ucsc_cgl/toil:3.6.0 and
cket/toil:3.5.0 are both examples of valid options. Note that since
Docker defaults to Dockerhub repos, only quay.io repos need to specify
their registry.

If quay.io/ucsc_cgl/toil:3.6.0 works, and the current version is 3.9.1,
then quay.io/ucsc_cgl/toil:3.9.1 really ought to work.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/BD2KGenomics/toil/issues/1831#issuecomment-322577241>,
or mute the thread

**Closed** 2018-04-12 19:09 UTC
Labels: ready
