### ISSUE TITLE
Spark master IP retrieved from wrong node

### ISSUE THREAD

**Issue by almussel** [BD2KGenomics/toil#1022] opened 2016-06-28 17:38 UTC
The `__init__` method of a service is not necessarily called from the same node as the service is actually run on. Because of this, the master IP of the spark cluster can't be determined in the `__init__` method. This manifests itself in connection failures once the service is running.

**Comment by fnothaft** [comment] 2016-06-28 17:40
Dupe of #1007; fixed by #1008. Closing.

**Closed by fnothaft** 2016-06-28 17:40 UTC
Labels: bug, spark/adam
