### ISSUE TITLE
Toil in singleMachine mode not loading the same module versions in worker processes as in master process

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1220] opened 2016-10-19 20:59 UTC
I have my own Python installation, meaning the Python global site packages directory, writable by me, is `~/python/lib/python2.7/site-packages`. I also have `~/.local/lib/python2.7/site-packages` where things installed with `pip install --user` go.

I recently set up a [new Toil-using pipeline](https://github.com/adamnovak/hgvm-builder), which requires Toil and some certain version of other packaged, and gets run via the `setup.py` entry points system. I installed it with `python setup.py develop`, which downloaded and installed the appropriate versions of all the dependencies.

The dependencies ended up in `~/python/lib/python2.7/site-packages`, but it turns out I had older versions of some dependencies in `~/.local/lib/python2.7/site-packages`. When invoking my pipeline through the entry point system, it would load the appropriate versions of all the dependencies from one directory, but then when Toil spins up its child processes in single machine mode, they end up loading the old versions of the dependencies from the other directory, leading to my code running with the wrong versions of some dependencies.

Just importing in `python -i` gives the old versions, and not the versions that were specifically installed as dependencies of this pipeline. I am pretty sure that the entry point system wrappers are doing something to provide my master script with exactly the versions of the modules it asked for in setup.py. But that's not happening in the worker processes.

Toil should integrate with the entry points system and crib off of the specific module version pointers it is using to load the exact module versions that were asked for in the pipeline's setup.py. Alternately, it should look at the module versions (or paths?) it is actually getting in the workers and make sure that they are in agreement with what it had on the master, to at least fail before some subtle module version difference causes a problem for the user script.

This might be solved by a virtualenv for this particular pipeline, but if you really do want to provide a global command-line tool to people through the entry points system, having people need to activate a virtualenv every time they log in, just because the tool internally uses Toil, is kind of a dealbreaker.

**Comment by hannes-ucsc** [comment] 2016-10-20 18:01
> Toil should integrate with the entry points system 

It does.

> and crib off of the specific module version pointers 

AFAIK, it can't. I think this is not a bug in Toil but inherent in Python's module lookup mechanism. We work around all of those issues by only supporting virtualenv. The documentation for this was just merged. If you think Toil is doing something wrong or something is missing, could you be more specific on what concrete behavior is wrong or missing? 

IOW, show me your sys.path and prove that something that appears later in sys.path is loaded in favor of sth that appears earlier.

> having people need to activate a virtualenv every time they log in

You don't need to activate a virtualenv explicitly, just running an entry point (or any other executable) from the venv's bin directory will activate it on the fly.

My general approach to this is this: Python's software deployment system sucks. I can back this up with facts if necessary. It's a can of worms and we can't support every possible scenario, especially considering the fact that we have to replicate software to each worker. We have a set of supported deployment scenarios and that's it. I'm not convinced that what you are proposing (if I understand what you are proposing because it's a little bit unspecific) is a use case with general utility.

**Comment by hannes-ucsc** [comment] 2016-10-20 18:03
These are the docs I was referring to:

http://toil.readthedocs.io/en/latest/developing.html#deploying-a-workflow

**Comment by hannes-ucsc** [comment] 2016-10-21 12:10
More thoughts:

> I am pretty sure that the entry point system wrappers are doing something to provide my master script with exactly the versions of the modules it asked for in setup.py

That's not my experience. The entry point's wrapper script (but I only know about console script entry points) only verifies the specific version of the package defining the entry point. Dependencies are not verified. So at best you get an error, but only an error (it does  not magically load the correct version if it appears somewhere else on sys.path) or no error at all if the wrong version of a dependency is loaded.

**Comment by adamnovak** [comment] 2016-10-25 18:14
I think the real problem is that setup.py (through setuptools?) and pip
can't agree on where packages should be installed. If they did agree, I
would only have one version anyway, I think, and this wouldn't be a problem.

**Closed** 2016-12-01 00:42 UTC
Labels: wontfix
