### ISSUE TITLE
Sort test fails if run from a regular rather than an editable install 

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#425] opened 2015-09-25 17:02 UTC
I tried to run `python setup.py test` on Kolossus yesterday afternoon, and forgot about it, and this morning I got an unhappy e-mail that I was using up all the CPU on Kolossus, and the tests still hadn't finished.

```
[anovak@kolossus toil]$ python setup.py test
running test
Searching for pytest==2.7.2
Reading https://pypi.python.org/simple/pytest/
Best match: pytest 2.7.2
Downloading https://pypi.python.org/packages/source/p/pytest/pytest-2.7.2.tar.gz#md5=dcd8e891474d605b81fc7fcc8711e95b
Processing pytest-2.7.2.tar.gz
Writing /scratch/tmp/easy_install-FP6ok_/pytest-2.7.2/setup.cfg
Running pytest-2.7.2/setup.py -q bdist_egg --dist-dir /scratch/tmp/easy_install-FP6ok_/pytest-2.7.2/egg-dist-tmp-rCVwyf

Installed /cluster/home/anovak/build/toil/pytest-2.7.2-py2.7.egg
Searching for py>=1.4.29
Reading https://pypi.python.org/simple/py/
Best match: py 1.4.30
Downloading https://pypi.python.org/packages/source/p/py/py-1.4.30.tar.gz#md5=a904aabfe4765cb754f2db84ec7bb03a
Processing py-1.4.30.tar.gz
Writing /scratch/tmp/easy_install-ZQw485/py-1.4.30/setup.cfg
Running py-1.4.30/setup.py -q bdist_egg --dist-dir /scratch/tmp/easy_install-ZQw485/py-1.4.30/egg-dist-tmp-zVbN63

Installed /cluster/home/anovak/build/toil/py-1.4.30-py2.7.egg
running egg_info
writing requirements to src/toil.egg-info/requires.txt
writing src/toil.egg-info/PKG-INFO
writing top-level names to src/toil.egg-info/top_level.txt
writing dependency_links to src/toil.egg-info/dependency_links.txt
writing entry points to src/toil.egg-info/entry_points.txt
reading manifest file 'src/toil.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/toil.egg-info/SOURCES.txt'
running build_ext
======================================================== test session starts ========================================================
platform linux2 -- Python 2.7.9 -- py-1.4.30 -- pytest-2.7.2
rootdir: /cluster/home/anovak/build/toil, inifile: setup.cfg
collected 87 items / 2 errors 

attic/absolute_imports.py F
src/toil/resource.py .
src/toil/jobStores/awsJobStore.py .
src/toil/jobStores/azureJobStore.py .
src/toil/test/batchSystems/batchSystemTest.py ssssssss................ssssssss
src/toil/test/dependencies/dependenciesTest.py x
src/toil/test/jobStores/jobStoreTest.py ........FFFF........ssss
src/toil/test/mesos/mesosTest.py ss
src/toil/test/sort/sortTest.py sFsF.ss^CFTerminated
```

Unless I've introduced a bug with all my Mesos hacking (which is possible), the tests should either be made faster, or be given an option to limit the total number of threads the tests will spawn.

**Comment by hannes-ucsc** [comment] 2015-09-25 17:17
The tests run on EC2 in about 1 hour and 6 minutes. From your logs it is not apparent whether they are just slow or hung. I think it is more likely that the tests are hung.

The sortTest has a loop builtin that reruns the workflow until all jobs succeed. The loop is necessary because the sort tests randomly fail jobs in order to test the resume functionality. So the sort test either succeeds or hangs. This is worth an issue in itself. If GridEngine or Parasol are misconfigured that can also contribute to test slowness. Please rerun on pristine sources and  ``--pytest-args "-s -vv src/toil/test/jobStores/jobStoreTest.py src/toil/test/sort/sortTest.py"`` so we can reduce the number of variables and get better output.

**Comment by joelarmstrong** [comment] 2015-09-25 17:32
Is this on hive? The old jobTree sort test used to fail miserably on hive, although that seemed to be fixed when the servers got patched a year ago.

**Comment by hannes-ucsc** [comment] 2015-09-29 02:40
Assigning to author for further info. Feel free to close this if you don't have the time to rerun the test on Kolossus. Maybe it's a good thing that Kolossus is being eaten.

**Comment by adamnovak** [comment] 2015-09-30 18:53
I don't actually have Toil on the Hive filesystem for this; it's on /cluster/home. Maybe it should be on hive?

Anyway, I've rerun with the given options, and it seems to indicate the problem:
```
[anovak@kolossus toil]$ python setup.py test --pytest-args "-s -vv src/toil/test/jobStores/jobStoreTest.py src/toil/test/sort/sortTest.py"
running test
running egg_info
writing requirements to src/toil.egg-info/requires.txt
writing src/toil.egg-info/PKG-INFO
writing top-level names to src/toil.egg-info/top_level.txt
writing dependency_links to src/toil.egg-info/dependency_links.txt
writing entry points to src/toil.egg-info/entry_points.txt
reading manifest file 'src/toil.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/toil.egg-info/SOURCES.txt'
running build_ext
============================= test session starts ==============================
platform linux2 -- Python 2.7.9 -- py-1.4.30 -- pytest-2.7.2 -- /cluster/home/anovak/python/bin/python
rootdir: /cluster/home/anovak/build/toil, inifile: setup.cfg
collected 37 items 

src/toil/test/jobStores/jobStoreTest.py::FileJobStoreTest::test PASSED
src/toil/test/jobStores/jobStoreTest.py::FileJobStoreTest::testFileDeletion PASSED
src/toil/test/jobStores/jobStoreTest.py::FileJobStoreTest::testMultipartUploads PASSED
src/toil/test/jobStores/jobStoreTest.py::FileJobStoreTest::testZeroLengthFiles PASSED
src/toil/test/jobStores/jobStoreTest.py::AWSJobStoreTest::test PASSED
src/toil/test/jobStores/jobStoreTest.py::AWSJobStoreTest::testFileDeletion PASSED
src/toil/test/jobStores/jobStoreTest.py::AWSJobStoreTest::testMultipartUploads PASSED
src/toil/test/jobStores/jobStoreTest.py::AWSJobStoreTest::testZeroLengthFiles PASSED
src/toil/test/jobStores/jobStoreTest.py::AzureJobStoreTest::test FAILED
src/toil/test/jobStores/jobStoreTest.py::AzureJobStoreTest::testFileDeletion FAILED
src/toil/test/jobStores/jobStoreTest.py::AzureJobStoreTest::testMultipartUploads FAILED
src/toil/test/jobStores/jobStoreTest.py::AzureJobStoreTest::testZeroLengthFiles FAILED
src/toil/test/jobStores/jobStoreTest.py::EncryptedFileJobStoreTest::test PASSED
src/toil/test/jobStores/jobStoreTest.py::EncryptedFileJobStoreTest::testFileDeletion PASSED
src/toil/test/jobStores/jobStoreTest.py::EncryptedFileJobStoreTest::testMultipartUploads PASSED
src/toil/test/jobStores/jobStoreTest.py::EncryptedFileJobStoreTest::testZeroLengthFiles PASSED
src/toil/test/jobStores/jobStoreTest.py::EncryptedAWSJobStoreTest::test PASSED
src/toil/test/jobStores/jobStoreTest.py::EncryptedAWSJobStoreTest::testFileDeletion PASSED
src/toil/test/jobStores/jobStoreTest.py::EncryptedAWSJobStoreTest::testMultipartUploads PASSED
src/toil/test/jobStores/jobStoreTest.py::EncryptedAWSJobStoreTest::testZeroLengthFiles PASSED
src/toil/test/jobStores/jobStoreTest.py::EncryptedAzureJobStoreTest::test SKIPPED
src/toil/test/jobStores/jobStoreTest.py::EncryptedAzureJobStoreTest::testFileDeletion SKIPPED
src/toil/test/jobStores/jobStoreTest.py::EncryptedAzureJobStoreTest::testMultipartUploads SKIPPED
src/toil/test/jobStores/jobStoreTest.py::EncryptedAzureJobStoreTest::testZeroLengthFiles SKIPPED
src/toil/test/sort/sortTest.py::SortTest::testAwsMesos <- ../../python/lib/python2.7/unittest/case.py SKIPPED
src/toil/test/sort/sortTest.py::SortTest::testAwsSingle No handlers could be found for logger "toil.resource"
ERROR:boto:400 Bad Request
ERROR:boto:<?xml version="1.0"?>
<Response><Errors><Error><Code>NoSuchDomain</Code><Message>The specified domain does not exist.</Message><BoxUsage>0.0000137200</BoxUsage></Error></Errors><RequestID>4c2c4a1e-43d3-0d04-56de-c6b8ec7f9279</RequestID></Response>
ERROR:boto:400 Bad Request
ERROR:boto:<?xml version="1.0"?>
<Response><Errors><Error><Code>NoSuchDomain</Code><Message>The specified domain does not exist.</Message><BoxUsage>0.0000137200</BoxUsage></Error></Errors><RequestID>dd009c75-47c2-60de-707a-0d55571a1f33</RequestID></Response>
WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (64).
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/cluster/home/anovak/build/toil/src', name='toil.job', extension='.py').
WARNING:toil.leader:The job seems to have left a log file, indicating failure: d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5
WARNING:toil.leader:Reporting file: d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	Traceback (most recent call last):
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	  File "/cluster/home/anovak/build/toil/src/toil/worker.py", line 241, in main
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	    jobStore=jobStore)
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 890, in _execute
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	    returnValues = self.run(fileStore)
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 998, in run
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	    userFunction = self._getUserFunction()
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 970, in _getUserFunction
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	    userFunctionModule = self._loadUserModule(self.userFunctionModule)
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 535, in _loadUserModule
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	    return importlib.import_module(userModule.name)
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	  File "/cluster/home/anovak/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	    __import__(name)
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	ImportError: No module named test.sort.sort
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	Exiting the worker because of a failed job on host kolossus
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	ERROR:__main__:Exiting the worker because of a failed job on host kolossus
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5 to 2
WARNING:toil.leader:d034eae4-c2cd-4aaa-9e86-7c6fabc6c6e5:	WARNING:toil.jobWrapper:We have increased the default memory of the failed job to 2147483648 bytes
```

It looks like the user script in the sort test is trying to import `test.sort.sort` and failing.

Possibly relevant information here is that I installed Toil as a normal module, not as an editable module, and the installed toil is not necessarily the same as the version I am testing. It is smart enough to import itself instead of whatever happens to be on the PYTHON_PATH, right?

**Comment by adamnovak** [comment] 2015-09-30 19:02
Re-running a `pip install --upgrade --user .` did not help.

**Comment by adamnovak** [comment] 2015-09-30 19:14
I'm re-assigning this to @hannes-ucsc because it looks like he wrote the user module loading code.

**Comment by hannes-ucsc** [comment] 2015-10-01 01:34
Thank you. This should be easy to reproduce now. I think the cause is that this was a regular install. Still needs to be fixed.

**Comment by hannes-ucsc** [comment] 2015-10-28 22:25
I can reproduce this. It happens when Toil is installed via pip *and* the tests are run from a separate working copy on which `make develop` was *not* run. The pip-installed copy originates from the sdist at PyPI and sdists by default exclude the test code. By printing __file__ in worker.py and run.py I confirmed that worker.py is loaded from the checkout while job.py is loaded from the pip-installed copy of Toil. One thing to note about Python's package loader is that it does not do an exhaustive search of all possible candidates. For `import foo.bar`, the first dir on sys.path that has a foo directory with and __init__.py will be used, even if that foo directory doesn't have a bar directory inside it. The import will fail, even if there is another sys.path entry that does have a foo with a bar in it.

This is not a recommended way of running the tests because who is to say that both installations have matching versions. My inclination is to either close this bug as "won't fix" unless I come up with A) an easy test for detecting the dual install or B) an easy way to pin the package loading into one location.

**Closed** 2015-11-02 00:35 UTC
Labels: bug, in progress
