### ISSUE TITLE
Tear down this FileStore

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#666] opened 2016-02-04 19:25 UTC
We welcome change and openness; for we believe that speed and efficiency go together, that the advance of computational genomics can only strengthen the cause of medicine worldwide. There is one sign the cgl can make that would be unmistakable, that would advance dramatically the cause of speed and efficiency. Director of Comparative Genomics Paten, if you seek simplicity, if you seek <insert cool noun here> for the cgl and the haussler dry lab, if you seek simplicity and an end to code redundancy, come here to this git. Dr. Paten, clone this git. Dr. Paten, tear down this FileStore!

**Comment by heuermh** [comment] 2016-02-04 19:38
Sweet, love the issue # too.  :)

**Comment by hannes-ucsc** [comment] 2016-02-04 22:54
Yes, LOL.

@arkal, do you want @benedictpaten to start working on this now or should he wait until you're done with the things we were talking about?

**Comment by arkal** [comment] 2016-02-04 22:58
lets wait just a little bit.

**Comment by arkal** [comment] 2016-02-04 23:31
Hahaha... I also realized I'm a bit of a hypocrite asking you to do this then asking you to wait a bit before doing so!

**Comment by hannes-ucsc** [comment] 2016-03-30 01:25
@arkal, this makes no sense to me. Can you explain what this is about?

**Comment by arkal** [comment] 2016-03-30 04:12
We were going to reduce job.filestore to a minimal class and make job.cachedfilestore the default.

**Comment by hannes-ucsc** [comment] 2016-03-30 21:22
Is this still relevant, then?

**Comment by arkal** [comment] 2016-03-31 20:52
yes

**Comment by hannes-ucsc** [comment] 2016-05-10 21:36
Remove old caching from FileStore. TBD where background writing goes.

**Comment by benedictpaten** [comment] 2016-05-11 05:36
Why is this assigned to me? I think this is for @arkal

**Comment by hannes-ucsc** [comment] 2016-05-11 17:36
You had agreed to be the assignee. But feel free to reassign.

**Comment by benedictpaten** [comment] 2016-05-11 18:05
Okay, reassigning to @arkal He is the logical person for this.

**Comment by hannes-ucsc** [comment] 2016-07-02 01:21
#1029 was created as a dupe of this, but the PR addressing it has already been merged. That's why I'm marking this as a duplicate even though #1029 really is the dupe.

@arkal, please let me know if my interpretation of the situation is wrong. And if you could check for existing tickets before creating a duplicate that would help avoid confusion like this in the future ;-)

**Comment by hannes-ucsc** [comment] 2016-07-02 01:23
https://github.com/arkal/toil/commit/ab3623c2b41d9d883f27c9c8b302b85b1dc80fdf

**Closed** 2016-07-02 01:23 UTC
Labels: caching, duplicate, ready

**Comment by arkal** [comment] 2016-07-02 18:37
It's kind of dupe-y. This one wanted to strip down the features in Job.FileStore whereas #1029 completely removed it. I should have referenced it. My bad!
