### ISSUE TITLE
Enforce the maximum disk Toil is allowed to use for a run

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#643] opened 2016-01-13 21:26 UTC
Currently config.maxDisk is used not at all or only to limit a disk requirement of a single job. It should in fact, like maxCores, limit the amount of disk that is in use by all concurrently running jobs on any worker at any time. It (and the other maxXyz options) should also support a ratio of initially free space.

**Comment by hannes-ucsc** [comment] 2016-01-14 00:19
Currently config.maxDisk is used not at all or only to limit a disk requirement of a single job. It should in fact, like maxCores, limit the amount of disk that is in use by all concurrently running jobs on any worker at any time. It (and the other maxXyz options) should also support a ratio of initially free space.

**Comment by hannes-ucsc** [comment] 2016-02-17 03:13
Docker or cgroups seems to me the only possible way to implement this but Docker is still working on disk quota support.

**Comment by hannes-ucsc** [comment] 2016-05-10 17:48
See also #240

**Comment by hannes-ucsc** [comment] 2016-05-10 20:00
Dupe of #240.

**Closed by hannes-ucsc** 2016-05-10 20:00 UTC
Labels: enhancement, epic
