### ISSUE TITLE
Module Index link is broken on Sphinx docs index page

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#611] opened 2015-12-04 21:21 UTC
http://toil.readthedocs.org/en/latest/py-modindex.html

This link is broken. We should have a way of browsing all the modules in the docs.

**Comment by cket** [comment] 2016-02-29 22:46
The fix has been merged into master but not yet into the 3.1.x branch which is displayed on read the docs

**Comment by hannes-ucsc** [comment] 2016-03-01 02:27
> Hmm, this is still broken on the doc site:

Who wrote this?

> The fix has been merged into master but not yet into the 3.1.x branch which is displayed on read the docs

It never will be merged into 3.1.x. Too big a change for a small issue.

However, the "latest" version on RTD (which is build from master) is also broken. The problem is that RTD does not invoke our Makefile. I think it still invokes the code in conf.py so we will have to move this logic

https://github.com/BD2KGenomics/toil/commit/455b6be4c815a1bff366e34934f74916f24578c6#diff-b67911656ef5d18c4ae36cb6741b7965R89

to conf.py. Care must be taken to do so idempotently so as to not be too invasive.

**Closed** 2016-04-06 22:51 UTC
Labels: bug, documentation, in progress
