### ISSUE TITLE
Files put in global file store not in global file store

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#365] opened 2015-09-03 22:18 UTC
I'm putting files in the global file store in a child job, returning their IDs thouugh the promise mechanism into the follow-on job's arguments, and then the follow-on job is complaining that it can't get the files.

The code I am using is here: https://github.com/adamnovak/hgvm/blob/a97b0cb3835fd81078a580ac17d2843659baf84c/getAltReads.py

The messages I am getting are here:
```
[anovak@kolossus hgvm]$ rm -Rf tree && ./getAltReads.py ./tree `pwd`/dl --maxCores 64 --regions BRCA1
Starting server
Server started
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/bake-off/hgvm', name='getAltReads', extension='.py').
Sending log from master
INFO:realtime:This is the master
INFO:toil.lib.bioio:Logging set at level: INFO
INFO:toil.common:Using the single machine batch system
INFO:toil.jobStores.fileJobStore:Jobstore directory is: /hive/users/anovak/ga4gh/bake-off/hgvm/tree
INFO:realtime:This is the master
INFO:toil.batchSystems.singleMachine:Setting up the thread pool with 640 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 64.
INFO:toil.common:Written the environment for the jobs to the environment file
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/cluster/home/anovak/.local/lib/python2.7/site-packages', name='toil.job', extension='.pyc').
INFO:toil.leader:Checked batch system has no running jobs and no updated jobs
INFO:toil.leader:Found 1 jobs to start and 0 jobs with successors to run
INFO:toil.leader:Starting the main loop
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree v/r/jobcI22fw'.
INFO:realtime:Starting download
INFO:realtime:Got 2 sample URLs
INFO:realtime:Making child for BRCA1 x NA06985: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06985
INFO:realtime:Making child for BRCA1 x NA06984: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06984
INFO:realtime:Done making children
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree i/L/jobrZzC1R'.
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree i/V/job4uJOM_'.
INFO:realtime:Supposed to download ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06985 ranges ['chr17:43044294-43125482'] to /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06985.bam
INFO:realtime:Supposed to download ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06984 ranges ['chr17:43044294-43125482'] to /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06984.bam
INFO:realtime:Need URLs: ['ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06985/alignment/NA06985.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram']
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree k/9/joblK0HtL'.
INFO:realtime:Need URLs: ['ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06984/alignment/NA06984.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram']
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree 4/d/jobCWAmtb'.
INFO:realtime:Trying to download chr17:43044294-43125482 from ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06985/alignment/NA06985.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram
INFO:realtime:Trying to download chr17:43044294-43125482 from ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06984/alignment/NA06984.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree 6/9/jobMjexml'.
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree u/C/jobHf0cen'.
INFO:realtime:Building /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06984.bam from IDs ['4/d/jobCWAmtb/g/tmpfbThnV.tmp']
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 6/9/jobMjexml
WARNING:toil.leader:Reporting file: 6/9/jobMjexml
WARNING:toil.leader:6/9/jobMjexml:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:6/9/jobMjexml:	INFO:toil.jobStores.fileJobStore:Jobstore directory is: /hive/users/anovak/ga4gh/bake-off/hgvm/tree
WARNING:toil.leader:6/9/jobMjexml:	WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/bake-off/hgvm/getAltReads.pyc'
WARNING:toil.leader:6/9/jobMjexml:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/bake-off/hgvm', name='getAltReads', extension='.pyc')
WARNING:toil.leader:6/9/jobMjexml:	INFO:realtime:Building /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06984.bam from IDs ['4/d/jobCWAmtb/g/tmpfbThnV.tmp']
WARNING:toil.leader:6/9/jobMjexml:	Traceback (most recent call last):
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py", line 238, in main
WARNING:toil.leader:6/9/jobMjexml:	    jobStore=jobStore)
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 862, in _execute
WARNING:toil.leader:6/9/jobMjexml:	    returnValues = self.run(fileStore)
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 983, in run
WARNING:toil.leader:6/9/jobMjexml:	    return userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:6/9/jobMjexml:	  File "/hive/users/anovak/ga4gh/bake-off/hgvm/getAltReads.py", line 480, in concatAndSortBams
WARNING:toil.leader:6/9/jobMjexml:	    input_files = [job.fileStore.readGlobalFile(bam_id) for bam_id in bam_ids]
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 399, in readGlobalFile
WARNING:toil.leader:6/9/jobMjexml:	    self.jobStore.readFile(fileStoreID, localFilePath)
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 157, in readFile
WARNING:toil.leader:6/9/jobMjexml:	    self._checkJobStoreFileID(jobStoreFileID)
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 293, in _checkJobStoreFileID
WARNING:toil.leader:6/9/jobMjexml:	    raise NoSuchFileException("File %s does not exist in jobStore" % jobStoreFileID)
WARNING:toil.leader:6/9/jobMjexml:	NoSuchFileException: The file 'File 4/d/jobCWAmtb/g/tmpfbThnV.tmp does not exist in jobStore' does not exist
WARNING:toil.leader:6/9/jobMjexml:	Exiting the worker because of a failed job on host kolossus
WARNING:toil.leader:6/9/jobMjexml:	ERROR:__main__:Exiting the worker because of a failed job on host kolossus
WARNING:toil.leader:6/9/jobMjexml:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 6/9/jobMjexml to 0
WARNING:toil.leader:Job: 6/9/jobMjexml is completely failed
INFO:realtime:Building /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06985.bam from IDs ['k/9/joblK0HtL/g/tmpXWMxPK.tmp']
WARNING:toil.leader:The job seems to have left a log file, indicating failure: u/C/jobHf0cen
WARNING:toil.leader:Reporting file: u/C/jobHf0cen
WARNING:toil.leader:u/C/jobHf0cen:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:u/C/jobHf0cen:	INFO:toil.jobStores.fileJobStore:Jobstore directory is: /hive/users/anovak/ga4gh/bake-off/hgvm/tree
WARNING:toil.leader:u/C/jobHf0cen:	WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/bake-off/hgvm/getAltReads.pyc'
WARNING:toil.leader:u/C/jobHf0cen:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/bake-off/hgvm', name='getAltReads', extension='.pyc')
WARNING:toil.leader:u/C/jobHf0cen:	INFO:realtime:Building /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06985.bam from IDs ['k/9/joblK0HtL/g/tmpXWMxPK.tmp']
WARNING:toil.leader:u/C/jobHf0cen:	Traceback (most recent call last):
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py", line 238, in main
WARNING:toil.leader:u/C/jobHf0cen:	    jobStore=jobStore)
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 862, in _execute
WARNING:toil.leader:u/C/jobHf0cen:	    returnValues = self.run(fileStore)
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 983, in run
WARNING:toil.leader:u/C/jobHf0cen:	    return userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:u/C/jobHf0cen:	  File "/hive/users/anovak/ga4gh/bake-off/hgvm/getAltReads.py", line 480, in concatAndSortBams
WARNING:toil.leader:u/C/jobHf0cen:	    input_files = [job.fileStore.readGlobalFile(bam_id) for bam_id in bam_ids]
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 399, in readGlobalFile
WARNING:toil.leader:u/C/jobHf0cen:	    self.jobStore.readFile(fileStoreID, localFilePath)
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 157, in readFile
WARNING:toil.leader:u/C/jobHf0cen:	    self._checkJobStoreFileID(jobStoreFileID)
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 293, in _checkJobStoreFileID
WARNING:toil.leader:u/C/jobHf0cen:	    raise NoSuchFileException("File %s does not exist in jobStore" % jobStoreFileID)
WARNING:toil.leader:u/C/jobHf0cen:	NoSuchFileException: The file 'File k/9/joblK0HtL/g/tmpXWMxPK.tmp does not exist in jobStore' does not exist
WARNING:toil.leader:u/C/jobHf0cen:	Exiting the worker because of a failed job on host kolossus
WARNING:toil.leader:u/C/jobHf0cen:	ERROR:__main__:Exiting the worker because of a failed job on host kolossus
WARNING:toil.leader:u/C/jobHf0cen:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job u/C/jobHf0cen to 0
WARNING:toil.leader:Job: u/C/jobHf0cen is completely failed
INFO:toil.leader:Only failed jobs and their dependents (2 total) are remaining, so exiting.
INFO:toil.leader:Finished the main loop
INFO:toil.leader:Waiting for stats and logging collator process to finish
INFO:toil.leader:Stats/logging finished collating in 0.019984960556 seconds
Traceback (most recent call last):
  File "./getAltReads.py", line 530, in <module>
    sys.exit(main())
  File "./getAltReads.py", line 524, in main
    Job.Runner.startToil(root_job,  options)
  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 356, in startToil
    return mainLoop(config, batchSystem, jobStore, rootJob)
  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/leader.py", line 508, in mainLoop
    raise FailedJobsException( config.jobStore, totalFailedJobs )
toil.leader.FailedJobsException: The job store '/hive/users/anovak/ga4gh/bake-off/hgvm/tree' contains 2 failed jobs
```

**Comment by adamnovak** [comment] 2015-09-03 22:39
The "global" files API backends into the `writeFile` method of the job store, which creates temporary files for the current job. So as soon as a job and its follow-ons finish, any global files they created are destroyed, whether the IDs have been passed up to parents' follow-ons or not.

**Comment by joelarmstrong** [comment] 2015-09-03 22:45
Hmm, yeah, that sucks. I think a way around that would be to create blank empty files in the parent, give those to its children to fill in, then concat them in the follow-on (where they are still valid).

**Comment by cket** [comment] 2015-09-03 23:23
Global is a bad name, it was meant to contrast with local files that no other job, including children, can access. We have private methods that write files into the jobStore that aren't associated with any particular job, so I'm not sure why we don't also have API for those kinds of 'persistent' files. I'll bring it up as a possible feature to add.

**Comment by hannes-ucsc** [comment] 2015-09-04 01:16
This will bite every new user. We need to rename "shared" to "global" and "global" to "".

At the same time we want to discourage the use of shared files, since they aren't cleaned up.

We also need to cleanup the inline docstrings, at least the user-facing ones, as some of them are incomprehensible at the moment.

**Comment by cket** [comment] 2015-09-04 19:04
Shorter script that reproduces the problem: 
http://pastebin.com/auqxkUEn
Weird behavior happens when you make the parent and child use the same amount of resources, causing the jobs to be chained. In that case, the follow on can access the file created by the child.

**Comment by benedictpaten** [comment] 2015-09-16 06:31
This is fixed in my pull request

**Comment by hannes-ucsc** [comment] 2015-09-16 08:31
What else needs to be done with this?

**Comment by hannes-ucsc** [comment] 2015-09-16 17:29
What else needs to be done here? Doesn't the PR resolve the issue?

**Comment by adamnovak** [comment] 2015-09-17 17:21
It looks like the new cleanup parameter in #397 should address this. I'm not sure about the design there (because Bool Parameters Are Bad), but it ought to work fine.

**Closed** 2015-09-20 01:23 UTC
Labels: bug, in progress
