### ISSUE TITLE
No such file error

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#146] opened 2015-07-08 23:09 UTC
WARNING:jobTree.leader:Reporting file: B/Z/jobfW0NrB
WARNING:jobTree.leader:B/Z/jobfW0NrB:	---JOBTREE WORKER OUTPUT LOG---
WARNING:jobTree.leader:B/Z/jobfW0NrB:	Next available file descriptor: 15
WARNING:jobTree.leader:B/Z/jobfW0NrB:	DEBUG:__main__:Next available file descriptor: 15
WARNING:jobTree.leader:B/Z/jobfW0NrB:	Parsed job
WARNING:jobTree.leader:B/Z/jobfW0NrB:	DEBUG:__main__:Parsed job
WARNING:jobTree.leader:B/Z/jobfW0NrB:	Traceback (most recent call last):
WARNING:jobTree.leader:B/Z/jobfW0NrB:	 File "/Users/cj/jobTree/src/jobTree/worker.py", line 365, in main
WARNING:jobTree.leader:B/Z/jobfW0NrB:	   jobStore.writeStatsAndLogging(ET.tostring(stats))
WARNING:jobTree.leader:B/Z/jobfW0NrB:	 File "/Users/cj/jobTree/src/jobTree/jobStores/fileJobStore.py", line 193, in writeStatsAndLogging
WARNING:jobTree.leader:B/Z/jobfW0NrB:	   os.rename(tempStatsFile, tempStatsFile[:-4]) #This operation is atomic
WARNING:jobTree.leader:B/Z/jobfW0NrB:	OSError: [Errno 2] No such file or directory
WARNING:jobTree.leader:B/Z/jobfW0NrB:	Exiting the worker because of a failed job on host dhcp-169-233-153-7.cruznet.ucsc.edu
WARNING:jobTree.leader:B/Z/jobfW0NrB:	ERROR:__main__:Exiting the worker because of a failed job on host dhcp-169-233-153-7.cruznet.ucsc.edu
WARNING:jobTree.leader:B/Z/jobfW0NrB:	WARNING:jobTree.job:Due to failure we are reducing the remaining retry count of job B/Z/jobfW0NrB to 99
DEBUG:jobTree.leader:Added job: B/Z/jobfW0NrB to active jobs

**Comment by cket** [comment] 2015-07-08 23:16
To replicate: use DAG-rebased branch, run StatsTest with success_ratio set to 1 in sort.py. I've run this several times, and seen the failure 1-3 times per test. The test ultimately succeeds. 

This is also similar to the errors that I am seeing when trying to run awsSortTest, although I have not yet pushed the syntax fixes necessary to get awsSortTest to start.

**Comment by benedictpaten** [comment] 2015-08-17 05:11
Is this still a bug?

**Comment by hannes-ucsc** [comment] 2015-08-17 17:06
@cket, can you please try to reproduce again?

**Comment by cket** [comment] 2015-08-17 17:22
I just reproduced this following the steps above, so it is still a a bug. Seems to be stats related, although they are being displayed successfully at the end.

**Comment by benedictpaten** [comment] 2015-08-20 16:02
I can't reproduce this on the master branch. I use sortTest.py, set retryCount=0 set successRatio=1 and enable stats as an option.

**Comment by benedictpaten** [comment] 2015-08-20 16:11
I am assigning to CJ, as I can't reproduce it and I've been through the logic and don't see the bug. As this code hasn't changed I suspect there is still a bug, I just can't trap it.

**Comment by cket** [comment] 2015-08-20 19:13
I tried reproducing this again and I can't. I am seeing new tracebacks complaining about restarting, but it is still completing so these seem to be expected:

Traceback (most recent call last):
  File "/Users/cj/toil/src/toil/test/sort/sort.py", line 113, in <module>
    main()
  File "/Users/cj/toil/src/toil/test/sort/sort.py", line 110, in main
    Job.Runner.startToil(Job.wrapJobFn(setup, options.fileToSort, int(options.N)), options)
  File "/Users/cj/toil/src/toil/job.py", line 354, in startToil
    with setupToil(options, userScript=job.getUserScript()) as (config, batchSystem, jobStore):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/cj/toil/src/toil/common.py", line 407, in setupToil
    jobStore = loadJobStore(config.jobStore, config=config)
  File "/Users/cj/toil/src/toil/common.py", line 376, in loadJobStore
    return FileJobStore( jobStoreArgs, config=config )
  File "/Users/cj/toil/src/toil/jobStores/fileJobStore.py", line 35, in __init__
    self._checkJobStoreCreation(config != None, os.path.exists(self.jobStoreDir), self.jobStoreDir)
  File "/Users/cj/toil/src/toil/jobStores/abstractJobStore.py", line 77, in _checkJobStoreCreation
    "else remove it to start from scratch" % jobStoreString)

**Comment by benedictpaten** [comment] 2015-08-21 04:57
Those are expected errors, which are being tested for. I think I worked out the source of the original error. It was stupid. When my PR for #256 is in this will be fixed.

**Closed** 2015-08-21 08:02 UTC
Labels: bug, discuss, in progress
