### ISSUE TITLE
Caching is not compatible with files contained in folders called by getLocalTempDir

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#486] opened 2015-10-12 00:41 UTC
For example,
```
A = job.wrapJobFn(a)
B = job.wrapJobFn(b, a.rv())
A.addChild(B)


def a(job):
	'''
	Align a file and return the filestoreID for the sam
	'''
	work_dir = job.getLocalTempDir()
	...
	output_file = bwa_alignment(fastqs, outputdir=work_dir)
	#  Since output_file is in the scope of localdir, it will be cached
	output_file = job.writeGlobalFile(output_file)
	return output_file

def b(job, samfile):
	'''
	Convert SAMFILE to bam
	'''
	work_dir = job.fileStore.getLocalTempDir()
	#  Since samfile is in cache, the copy to samfile is passed
    samfile = job.readGlobalFile(samfile, os.path.join(work_dir, 'samfile.sam'))
    output_file =sam_To_bam(samfile, outputdir=work_dir)
    output_file = job.writeGlobalFile(output_file)
	return output_file
```

job B receives the cached copy of samfile which is in a folder returned by getLocalTempDir. While B starts its processing, A is actively deleting the temp local dir and B effectively processes a truncated version of samfile.

Using cache=False in readGlobalFile doesn't help because of line 544 in job.py
```
                    #If caching is not true then make a copy of the file
                    localFilePath = userPath if userPath != None else self.getLocalTempFile()
                    shutil.copyfile(cachedAbsFilePath, localFilePath)
                    return localFilePath
```
Even if i say don't use cache it copies the cached version of the file to work_dir.

**Comment by benedictpaten** [comment] 2015-10-12 13:40
Obviously this is a bug. cleanLocalTempDir is only supposed to remove non cached files and to prune the cache BEFORE b is run, and nothing should be removed subsequently. Chasing down this bug now. Bit confused because test fileStore test should have caught this bug.

**Comment by benedictpaten** [comment] 2015-10-12 13:47
Hi arjun, I can't reproduce this logic. The temporary file directories are not deleted concurrently with b, they are deleted before b is run. Can you please make a regression test with the bug and I will fix. I'm still confused how this could occur, given that the file store tests pass.

**Comment by benedictpaten** [comment] 2015-10-12 13:48
Assigning to arjun to create a test case.

**Comment by benedictpaten** [comment] 2015-10-12 13:54
PS, beefed up test/src/jobFileStoreTest.py to handle Arjun's case of using getLocalTempDir in associated pull request. However, this does not fix Arjun's error, just improves the test. Note I can not reproduce Arjun's error.

**Comment by arkal** [comment] 2015-10-12 17:29
I'm running the test now. Will post it ASA it checks out

**Comment by benedictpaten** [comment] 2015-10-20 00:12
This bug is not accurate, closing.

**Closed** 2015-10-20 00:12 UTC
Labels: bug
