### ISSUE TITLE
HTTP Error 400: Bad Request on Toil Restart

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil#1205] opened 2016-10-11 21:43 UTC
`~/.boto` credentials were on the leader at the start of the run. The run finished with a few failed jobs (~24 hours later) so I ran it with `--restart`.  I then saw this identical error message 10 times (`retryCount=1`) for 24 failed jobs.

```
 ---TOIL WORKER OUTPUT LOG---
 WARNING:toil.resource:The localize() method should only be invoked on a worker.
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 316, in main
     job = Job._loadJob(jobWrapper.command, jobStore)
   File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 624, in _loadJob
     userModule = cls._loadUserModule(userModule)
   File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 594, in _loadUserModule
     userModule = userModule.localize()
   File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 454, in localize
     resource.download(callback=stash)
   File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 163, in download
     self._save(tempDirPath)
   File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 281, in _save
     self._download(bytesIO)
   File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 234, in _download
     with closing(urlopen(self.url)) as content:
   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
     return opener.open(url, data, timeout)
   File "/usr/lib/python2.7/urllib2.py", line 435, in open
     response = meth(req, response)
   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
     'http', request, response, code, msg, hdrs)
   File "/usr/lib/python2.7/urllib2.py", line 473, in error
     return self._call_chain(*args)
   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
     result = func(*args)
   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
 HTTPError: HTTP Error 400: Bad Request
 Exiting the worker because of a failed jobWrapper on host ip-172-31-25-116
 ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-17 2-31-25-116
 WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job ee8b2977-2079-4c98-bc8a-3693858f7184 to 0
```

**Comment by hannes-ucsc** [comment] 2016-10-12 06:40
Are you absolutely certain that `~/.boto` contained valid credentials? I started recommending moving credentials from `~/.boto` to `~/.aws/credential` a while back. Maybe you followed my advice and ~/.boto didn't have any credentials in it?

**Comment by cket** [comment] 2016-12-01 00:57
Duplicate of #668

**Closed** 2016-12-01 00:57 UTC
Labels: aws, bug, hotdeployment, need info
