### ISSUE TITLE
Job fails complaining there's not enough space for caching when there is plenty

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1124] opened 2016-08-26 23:42 UTC
I'm trying to run a pipeline I used to run on older versions of Toil, and it seems that something about the caching feature addition broke it.

I'm running on a Mesos cluster on Azure, deployed through the big blue deploy-to-azure button that Toil provides.

The error I get looks like this:

```
WARNING:toil.leader:Reporting file: 39f4fec3_3a7a_4f64_b5b9_5412096060e6
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:       ---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:       Traceback (most recent call last):
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:         File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 
327, in main
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:           with fileStore.open(job):
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:         File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:           return self.gen.next()
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:         File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", li
ne 127, in open
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:           self.cleanCache(jobReqs)
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:         File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", li
ne 860, in cleanCache
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:           assert cacheInfo.isBalanced(), 'Unable to free up enough space fo
r caching.'
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:       AssertionError: Unable to free up enough space for caching.
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:       Exiting the worker because of a failed jobWrapper on host amn1agent2
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:       ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host amn1agent2
WARNING:toil.leader:39f4fec3_3a7a_4f64_b5b9_5412096060e6:       WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 39f4fec3_3a7a_4f64_b5b9_5412096060e6 to 0
WARNING:toil.leader:Job: 39f4fec3_3a7a_4f64_b5b9_5412096060e6 is completely failed
```

[My script is here.](https://github.com/adamnovak/hgvm-graph-bakeoff-evaluations/blob/266362e6b4df3a9e860481f247278fd443046efe/scripts/parallelMappingEvaluation.py) Note that the largest job is asking for 50 gigs of disk.

My disk usage on the master looks like this:

```
Filesystem      Size  Used Avail Use% Mounted on
udev            6.9G   12K  6.9G   1% /dev
tmpfs           1.4G  420K  1.4G   1% /run
/dev/sda1        29G  3.0G   25G  11% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            6.9G     0  6.9G   0% /run/shm
none            100M     0  100M   0% /run/user
none             64K     0   64K   0% /etc/network/interfaces.dynamic.d
/dev/sdb1       133G   60M  126G   1% /mnt
```

And on the workers it looks like this:

```
Filesystem      Size  Used Avail Use% Mounted on
udev            221G   12K  221G   1% /dev
tmpfs            45G  416K   45G   1% /run
/dev/sda1        29G  2.4G   26G   9% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            221G     0  221G   0% /run/shm
none            100M     0  100M   0% /run/user
none             64K     0   64K   0% /etc/network/interfaces.dynamic.d
/dev/sdb1       6.0T   56M  5.7T   1% /mnt
```

Note that there's not much room on the root disks, but Mesos is set to use the /mnt scratch disks for storage for tasks. Mesos clearly knows it has loads of disk space to offer:

![mesos space](https://cloud.githubusercontent.com/assets/5062495/18023252/b6dd9180-6bab-11e6-9da8-a28c290180ad.png)

I think Toil is either getting confused that the free space isn't where it thinks it needs it, or is set to cache to the wrong mountpoint and not communicating with Mesos correctly.

Since this pipeline worked before just fine, is there an option or something to disable caching (or just the free space check)? Is there an option or config setting to tell Toil where to put its cache?

Please let me know the best workaround (maybe telling Toil that my jobs don't need any disk?), as we want to run this pipeline somewhat urgently.

**Comment by adamnovak** [comment] 2016-08-26 23:52
Here's some more log info with debug on:

```
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.job:Getting JobFunctionWrappingJob from module toil.job.
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.job:Getting defaultdict from module collections.
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.job:Getting list from module __builtin__.
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.job:Getting Namespace from module argparse.
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.job:Getting ModuleDescriptor from module toil.resource.
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.job:Getting set from module __builtin__.
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.fileStore:CACHE: Obtained lock on file /tmp/toil-c68a6cb1-6ecc-4255-8a97-4a8bffdfdcfe/cache-c68a6cb1-6ecc-4255-8a97-4a8bffdfdcfe/.cacheLock
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.fileStore:CACHE: Released lock
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.fileStore:CACHE: Obtained lock on file /tmp/toil-c68a6cb1-6ecc-4255-8a97-4a8bffdfdcfe/cache-c68a6cb1-6ecc-4255-8a97-4a8bffdfdcfe/.cacheLock
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.fileStore:CACHE: Released lock
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.fileStore:CACHE: Obtained lock on file /tmp/toil-c68a6cb1-6ecc-4255-8a97-4a8bffdfdcfe/cache-c68a6cb1-6ecc-4255-8a97-4a8bffdfdcfe/.cacheLock
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.fileStore:CACHE: Need 53687091200 bytes for new job. Have 0
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.fileStore:CACHE: Evicting files to make room for the new job.
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       DEBUG:toil.fileStore:CACHE: Released lock
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       Traceback (most recent call last):
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:         File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 327, in main
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:           with fileStore.open(job):
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:         File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:           return self.gen.next()
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:         File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 127, in open
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:           self.cleanCache(jobReqs)
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:         File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 860, in cleanCache
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:           assert cacheInfo.isBalanced(), 'Unable to free up enough space for caching.'
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       AssertionError: Unable to free up enough space for caching.
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       Exiting the worker because of a failed jobWrapper on host amn1agent3
WARNING:toil.leader:33768d5a_a714_4baf_9c0d_2202f47aafc1:       ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host amn1agent3
```

I definitely told Mesos to use `/mnt` as its `work_dir` for jobs: https://github.com/BD2KGenomics/toil/blob/f770353faa8355990834145ccda8bf1f64bd00db/contrib/azure/configure-mesos-cluster.sh#L339-L340 According to [the Mesos docs](http://mesos.apache.org/documentation/latest/configuration/), there are supposed to be executor sandboxes under there that the tasks work in.

Why is Toil ignoring Mesos and wandering into /tmp?

**Comment by adamnovak** [comment] 2016-08-26 23:54
@arkal You wrote caching, right?

**Comment by arkal** [comment] 2016-08-27 00:06
How are you running the program? Are you specifying `--workDir /mnt/somewhere` ?

**Comment by adamnovak** [comment] 2016-08-28 19:50
Nope. I'm just pointing Toil at the Mesos master and telling it to use the
Mesos batch system. Do I have to give Toil a `--workDir` option to control
where it writes its temp files?

I figure that since Mesos is in charge of offering disk space to the Toil
jobs, Mesos should be telling the Toil executor where the disk space it was
offered actually lives on the node's filesystem, once it gets there. But I
can manually point Toil at the correct temp directory to use if it doesn't
know how to read Mesos's instructions, or if Mesos isn't actually trying to
communicate the appropriate path.

**Comment by arkal** [comment] 2016-08-29 16:58
I think that might be a decent feature to add in -- If `--workDir` is not specified but the batch system is Mesos, then get the workDir from Mesos.

Your problem in this issue is that your value for `$TMPDIR` is probably `/tmp` or something on the root directory, and not on the `/mnt` device. You can fix this by
a) specify `--workDir /mnt/somewhere` in your command line call on the leader
b) set the env variable `$TOIL_WORKDIR` to be `/mnt/somewhere` on every worker and NOT specify `workDir` on the command line. You can just add the line `$TOIL_WORKDIR=/mnt/somewhere` into your `/etc/environment` as root

**Comment by adamnovak** [comment] 2016-08-29 17:14
Maybe we should work one of the environment variable based ones into the
Toil azure setup script under contrib; the default settings ought to be
smart.

I do think that the Right Way to do it is to grab workDir from Mesos,
though, in case someone is using their own Mesos setup.

**Comment by adamnovak** [comment] 2016-08-29 20:13
I've tried this and it looks like just setting TOIL_WORK_DIR to /mnt won't work, because the Toil jobs don't run as root and thus don't have permission to write to that directory. Setting up the permissions properly would require just as much dedicated scripting in the Mesos cluster setup as setting up a dedicated /mnt/tmp.

I think it might not be worth having a workaround in our Mesos setup script; Toil should just listen to Mesos and pick up its work directory from there.

**Comment by hannes-ucsc** [comment] 2016-08-29 21:21
I think Mesos sets the current working directory to the sandbox before launching. Maybe we should default os.getcwd() for `TOIL_WORKDIR`? And its `TOIL_WORKDIR` not `TOIL_WORK_DIR`, btw.

**Comment by hannes-ucsc** [comment] 2016-08-29 21:21
… before launching the executor, that is.

**Comment by adamnovak** [comment] 2016-08-29 23:10
I've tried that in https://github.com/adamnovak/toil/commit/88d8cd481bdf3280a0853c8bcc8d425a2008b5b9 and I will see how it works, as soon as I get a chance to re-deploy the cluster.

**Comment by arkal** [comment] 2016-08-29 23:22
> I think Mesos sets the current working directory to the sandbox before launching. Maybe we should default os.getcwd() for TOIL_WORKDIR? And its TOIL_WORKDIR not TOIL_WORK_DIR, btw.

That might work. That might require us to rewrite parts of worker.py and put logic in there.

>I've tried this and it looks like just setting TOIL_WORK_DIR

As @hannes-ucsc mentioned, it's `TOIL_WORKDIR` and not `TOIL_WORK_DIR`. 

>Setting up the permissions properly would require just as much dedicated scripting in the Mesos cluster setup as setting up a dedicated /mnt/tmp.

If you look at `cgcloud` and `toil-latest-box`, `/var/lib/toil` is mounted on `/mnt/ephemeral`. The `mesosbox` user doesn't  have access to `/mtn/ephemeral` however `/var/lib/toil` is fully accessible by `mesosbox`. I could suggest doing something similar during cluster setup for your Azure instances.

**Comment by hannes-ucsc** [comment] 2016-09-15 01:10
Closing as duplicate of #1143. Please reopen if that is not correct.

**Closed** 2016-09-15 01:10 UTC
Labels: azure, mesos
