### ISSUE TITLE
Assertion error in bindBucket

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1357] opened 2016-12-01 18:56 UTC
File "/mnt/ephemeral/workspace/toil-branches/master/src/toil/jobStores/aws/jobStore.py", line 701, in _bindBucket
    assert versioning is self.__getBucketVersioning(bucket)
AssertionError: assert True is <bound method AWSJobStore.__getBucketVersioning of <toil.jobStores.aws.jobStore.AWSJobStore object at 0x2aac16b295d0>>(<Bucket: sort-test-0949fa27-0e98-442b-8f22-bd4b9ed416f6--files>)

Seen on a master build:
http://jenkins.cgcloud.info/job/toil-branches/branch/master/293/testReport/junit/src.toil.test.sort.sortTest/SortTest/testAwsSingle/

**Comment by hannes-ucsc** [comment] 2016-12-01 18:58
Looks like a dupe of #1227

**Closed** 2016-12-01 18:59 UTC
Labels: bug, duplicate
